# Generated by Django 3.0.5 on 2020-07-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20200704_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='offer',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='p4',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
